// Mensagens da Parte 4: a mesma calculadora das Partes 1 e 2, serializada em
// binário. Cada mensagem trafega no TCP precedida do seu tamanho em varint
// (formato "delimited" do protobuf), pois o TCP não preserva fronteiras.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/protocalc/calcpb/calc.proto

package calcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Operator substitui o símbolo textual (+, -, *, /). O valor zero é reservado
// para "não informado", como recomenda o guia de estilo do proto3, e o servidor
// o rejeita como operação inválida.
type Operator int32

const (
	Operator_OPERATOR_UNSPECIFIED Operator = 0
	Operator_OPERATOR_ADD         Operator = 1
	Operator_OPERATOR_SUBTRACT    Operator = 2
	Operator_OPERATOR_MULTIPLY    Operator = 3
	Operator_OPERATOR_DIVIDE      Operator = 4
)

// Enum value maps for Operator.
var (
	Operator_name = map[int32]string{
		0: "OPERATOR_UNSPECIFIED",
		1: "OPERATOR_ADD",
		2: "OPERATOR_SUBTRACT",
		3: "OPERATOR_MULTIPLY",
		4: "OPERATOR_DIVIDE",
	}
	Operator_value = map[string]int32{
		"OPERATOR_UNSPECIFIED": 0,
		"OPERATOR_ADD":         1,
		"OPERATOR_SUBTRACT":    2,
		"OPERATOR_MULTIPLY":    3,
		"OPERATOR_DIVIDE":      4,
	}
)

func (x Operator) Enum() *Operator {
	p := new(Operator)
	*p = x
	return p
}

func (x Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocalc_calcpb_calc_proto_enumTypes[0].Descriptor()
}

func (Operator) Type() protoreflect.EnumType {
	return &file_internal_protocalc_calcpb_calc_proto_enumTypes[0]
}

func (x Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operator.Descriptor instead.
func (Operator) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocalc_calcpb_calc_proto_rawDescGZIP(), []int{0}
}

// CalcRequest equivale a CALC:<n>:<operando1>:<op>:<operando2>.
type CalcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Left          float64                `protobuf:"fixed64,2,opt,name=left,proto3" json:"left,omitempty"`
	Op            Operator               `protobuf:"varint,3,opt,name=op,proto3,enum=calc.v1.Operator" json:"op,omitempty"`
	Right         float64                `protobuf:"fixed64,4,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcRequest) Reset() {
	*x = CalcRequest{}
	mi := &file_internal_protocalc_calcpb_calc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcRequest) ProtoMessage() {}

func (x *CalcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocalc_calcpb_calc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcRequest.ProtoReflect.Descriptor instead.
func (*CalcRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocalc_calcpb_calc_proto_rawDescGZIP(), []int{0}
}

func (x *CalcRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *CalcRequest) GetLeft() float64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *CalcRequest) GetOp() Operator {
	if x != nil {
		return x.Op
	}
	return Operator_OPERATOR_UNSPECIFIED
}

func (x *CalcRequest) GetRight() float64 {
	if x != nil {
		return x.Right
	}
	return 0
}

// CalcResponse equivale a RESULT:<n>:<resultado> ou ERROR:<n>:<mensagem>;
// o oneof garante que apenas um dos dois esteja presente.
type CalcResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*CalcResponse_Result
	//	*CalcResponse_Error
	Outcome       isCalcResponse_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcResponse) Reset() {
	*x = CalcResponse{}
	mi := &file_internal_protocalc_calcpb_calc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcResponse) ProtoMessage() {}

func (x *CalcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocalc_calcpb_calc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcResponse.ProtoReflect.Descriptor instead.
func (*CalcResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocalc_calcpb_calc_proto_rawDescGZIP(), []int{1}
}

func (x *CalcResponse) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *CalcResponse) GetOutcome() isCalcResponse_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *CalcResponse) GetResult() float64 {
	if x != nil {
		if x, ok := x.Outcome.(*CalcResponse_Result); ok {
			return x.Result
		}
	}
	return 0
}

func (x *CalcResponse) GetError() string {
	if x != nil {
		if x, ok := x.Outcome.(*CalcResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isCalcResponse_Outcome interface {
	isCalcResponse_Outcome()
}

type CalcResponse_Result struct {
	Result float64 `protobuf:"fixed64,2,opt,name=result,proto3,oneof"`
}

type CalcResponse_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*CalcResponse_Result) isCalcResponse_Outcome() {}

func (*CalcResponse_Error) isCalcResponse_Outcome() {}

var File_internal_protocalc_calcpb_calc_proto protoreflect.FileDescriptor

const file_internal_protocalc_calcpb_calc_proto_rawDesc = "" +
	"\n" +
	"$internal/protocalc/calcpb/calc.proto\x12\acalc.v1\"l\n" +
	"\vCalcRequest\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04left\x18\x02 \x01(\x01R\x04left\x12!\n" +
	"\x02op\x18\x03 \x01(\x0e2\x11.calc.v1.OperatorR\x02op\x12\x14\n" +
	"\x05right\x18\x04 \x01(\x01R\x05right\"]\n" +
	"\fCalcResponse\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x18\n" +
	"\x06result\x18\x02 \x01(\x01H\x00R\x06result\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05errorB\t\n" +
	"\aoutcome*y\n" +
	"\bOperator\x12\x18\n" +
	"\x14OPERATOR_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fOPERATOR_ADD\x10\x01\x12\x15\n" +
	"\x11OPERATOR_SUBTRACT\x10\x02\x12\x15\n" +
	"\x11OPERATOR_MULTIPLY\x10\x03\x12\x13\n" +
	"\x0fOPERATOR_DIVIDE\x10\x04B'Z%calcsockets/internal/protocalc/calcpbb\x06proto3"

var (
	file_internal_protocalc_calcpb_calc_proto_rawDescOnce sync.Once
	file_internal_protocalc_calcpb_calc_proto_rawDescData []byte
)

func file_internal_protocalc_calcpb_calc_proto_rawDescGZIP() []byte {
	file_internal_protocalc_calcpb_calc_proto_rawDescOnce.Do(func() {
		file_internal_protocalc_calcpb_calc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocalc_calcpb_calc_proto_rawDesc), len(file_internal_protocalc_calcpb_calc_proto_rawDesc)))
	})
	return file_internal_protocalc_calcpb_calc_proto_rawDescData
}

var file_internal_protocalc_calcpb_calc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_protocalc_calcpb_calc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_protocalc_calcpb_calc_proto_goTypes = []any{
	(Operator)(0),        // 0: calc.v1.Operator
	(*CalcRequest)(nil),  // 1: calc.v1.CalcRequest
	(*CalcResponse)(nil), // 2: calc.v1.CalcResponse
}
var file_internal_protocalc_calcpb_calc_proto_depIdxs = []int32{
	0, // 0: calc.v1.CalcRequest.op:type_name -> calc.v1.Operator
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_protocalc_calcpb_calc_proto_init() }
func file_internal_protocalc_calcpb_calc_proto_init() {
	if File_internal_protocalc_calcpb_calc_proto != nil {
		return
	}
	file_internal_protocalc_calcpb_calc_proto_msgTypes[1].OneofWrappers = []any{
		(*CalcResponse_Result)(nil),
		(*CalcResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocalc_calcpb_calc_proto_rawDesc), len(file_internal_protocalc_calcpb_calc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocalc_calcpb_calc_proto_goTypes,
		DependencyIndexes: file_internal_protocalc_calcpb_calc_proto_depIdxs,
		EnumInfos:         file_internal_protocalc_calcpb_calc_proto_enumTypes,
		MessageInfos:      file_internal_protocalc_calcpb_calc_proto_msgTypes,
	}.Build()
	File_internal_protocalc_calcpb_calc_proto = out.File
	file_internal_protocalc_calcpb_calc_proto_goTypes = nil
	file_internal_protocalc_calcpb_calc_proto_depIdxs = nil
}
